apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: guestbook-simple-dev
images:
- name: ghcr.io/initcron/guestbook
  newTag: v1.0.4
patches:
- path: guestbook-svc.yaml
